<a href="https://colab.research.google.com/github/AdrianSchmidt96/PythonProjects/blob/main/Wprowadzenie/%20numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1D** **ARRAY**

In [1]:
import numpy as np
np.__version__

'2.0.2'

In [2]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

In [3]:
x = np.array([1,3])

In [4]:
print(x)

[1 3]


In [5]:
x.ndim

1

In [6]:
x.shape

(2,)

In [7]:
x.size

2

In [8]:
x.dtype

dtype('int64')

In [9]:
x = np.array([1.3,2.3,1.4])

In [10]:
print(x)

[1.3 2.3 1.4]


**2D ARRAY**

In [11]:
x = np.array([[1,2],[-3,1]])
print(x)

[[ 1  2]
 [-3  1]]


In [12]:
x.ndim

2

In [13]:
x.shape

(2, 2)

In [14]:
x = np.array([[1,2,3],[1,3,4]])
print(x)

[[1 2 3]
 [1 3 4]]


In [15]:
x.shape

(2, 3)

**3D ARRAY**

In [16]:
x = np.array(
    [[[4,5,1],
      [3,3,3]],

    [[3,4,4],
     [1,2,3]]]
)

print(x)

[[[4 5 1]
  [3 3 3]]

 [[3 4 4]
  [1 2 3]]]


In [17]:
x.ndim

3

Poniżej shape jest takie ponieważ, mamy 2 tablice 2 wiersze po 3 kolumny

In [18]:
x.shape

(2, 2, 3)

**TYPY DANYCH**

In [19]:
a = np.array([1,2,3])
a.dtype

dtype('int64')

In [20]:
a = np.array([1.0,2.3,3.3])
a.dtype

dtype('float64')

In [21]:
a = np.array([1,2,1], dtype ='float' )
a.dtype


dtype('float64')

In [22]:
a

array([1., 2., 1.])

In [23]:
a = np.array([1,2,1], dtype ='complex' )
a.dtype


dtype('complex128')

In [24]:
a = np.array([1,2,1], dtype ='int' )
a.dtype


dtype('int64')

In [25]:
a = np.array([1,2,1], dtype =np.int8 )
a.dtype


dtype('int8')

In [26]:
a = np.array([1,2,1], dtype =np.uint8 )
a.dtype


dtype('uint8')

**Tworzenie Tablic**

In [27]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [29]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
np.full(shape=(3,3), fill_value=4,dtype = 'int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(start= 5,stop=10)

array([5, 6, 7, 8, 9])

In [33]:
np.arange(start= 5,stop=100,step=10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [34]:
np.linspace(start=0,stop=1,num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [35]:
a = np.arange(15)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**FAJNE ZASTOSOWANE**

In [36]:
a.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

**Dzięki poniższemu tzn. -1 python sam dobiera odpowiedni rozkład**


In [37]:
a.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

**Podstawowe Operacje na tablicach**

In [38]:
a = np.array([3,1,4,2])
b = np.array([3,-1,3,2])
print(a)
print(b)

[3 1 4 2]
[ 3 -1  3  2]


**Dodają się do siebie wartości, wszelkie działania matematyczne wykonują się na sobie tzn 1 pozycja z A + 1 pozycja z B
**

In [39]:
a+b

array([6, 0, 7, 4])

****Dodanie 3 do każdej wartości tablicy, możemy też odejmować itd...*** *

In [40]:
a+3

array([6, 4, 7, 5])

In [41]:
a*3*b

array([27, -3, 36, 12])

***MNOŻENIE MACIEŻOWE** *

In [42]:
x=np.array([[1,3],[-2,0]])
y=np.array([[6,0],[-1,2]])

In [43]:
np.dot(x,y)

array([[  3,   6],
       [-12,   0]])

**Generowanie liczb pseudolosowych**

In [44]:
np.random.seed(0)

In [46]:
np.random.randn()

1.764052345967664

In [48]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [49]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [50]:
np.random.rand()

0.1965823616800535

In [51]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [52]:
np.random.rand(10,2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [53]:
np.random.randint(10)

3

In [54]:
np.random.randint(low=10, high=101)

56

In [55]:
np.random.randint(low=10, high=101, size = 20)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50, 82, 29, 82, 36, 76, 62, 77,
       71, 24, 14])

In [56]:
np.random.choice([4,2,1,3,5])

np.int64(3)

In [57]:
np.random.choice(['python', 'java','sql'])

np.str_('java')

In [62]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.random.shuffle(data)
data

array([3, 0, 6, 1, 2, 4, 9, 8, 5, 7])

**Podsatwowe Funkcje**

In [64]:
np.exp(1)

np.float64(2.718281828459045)

In [66]:
np.sqrt(9)

np.float64(3.0)

In [67]:
np.all([2,3,1])

np.True_

In [68]:
np.any([1,2,1])

np.True_

In [69]:
np.any([0,0,0])

np.False_

In [70]:
a = np.random.rand(5)
a

array([0.47486752, 0.47013219, 0.71607453, 0.287991  , 0.38346223])

In [71]:
np.argmax(a)  #zwraca z powyższego największą


np.int64(2)

In [72]:
np.argmin(a) #zwraca najniższą

np.int64(3)

In [73]:
np.argsort(a) #sortuje po ID

array([3, 4, 1, 0, 2])

In [74]:
np.min(a) #minimalna

np.float64(0.2879910043632805)

In [75]:
np.mean(a)#średnia

np.float64(0.4665054930583158)

In [77]:
np.std(a) #odchylenie standardowe

np.float64(0.14221911840144003)

np.float64(0.14221911840144003)

**Indeksowania, Wycinanie**

In [80]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# możliwe indeksowanie np: a[index], a[start: stop], a[:stop], a[start:]

In [81]:
a[2]

np.int64(2)

In [82]:
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [83]:
a[:2]

array([0, 1])

In [84]:
a[[0,2]]#wycinanie konkretne

array([0, 2])

In [85]:
a[-1]

np.int64(19)

In [86]:
a[10:15]

array([10, 11, 12, 13, 14])

In [89]:
a= a.reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [90]:
a[0]# wytniemy 1 wiersz

array([0, 1, 2, 3, 4])

In [92]:
a[:,0] # wytniemy 1 kolumnę

array([ 0,  5, 10, 15])

In [93]:
a[1,1]#wycinanie konkretnej liczby

np.int64(6)

In [95]:
a[1:2, 3:6] #wycinanie konkretnego wycinka tj

array([[8, 9]])

In [97]:
a[1,2] = 14 #zmiana przypisania z 7 na 14

In [98]:
a#widoczna zmiana

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

**Iteracja po tablicach**

In [99]:
for row in a:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [102]:
for row in a:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [104]:
for item in a.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [105]:
a.shape

(4, 5)

In [106]:
a.reshape(5,4) #zmiana układu

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [108]:
a.ravel() #spłaczenie tablicy

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [111]:
a = np.arange(start= -10, stop = 10, step = 0.5)
a

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [114]:
a = a.reshape(10,-1)

In [115]:
a > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [116]:
a [ a> 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [117]:
np.bitwise_and(a > -5, a < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [118]:
np.bitwise_or(a < -5, a > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])